package zedegri;

public enum EnemyAttackType {
    TEAM_HEAL,
    HEAL,
    LEECH,
    HEAVY_PHYSICAL_ATTACK,
    HEAVY_ETHER_ATTACK,
    PHYSICAL_DEFENSE_UP,
    ETHER_DEFENSE_UP,
    DAZE,
    FLICKER,
    PHYSICAL_ATTACK_UP_2,
    PHYSICAL_ATTACK_UP_15,
    POTENTIAL_UP_2,
    POTENTIAL_UP_15,
    PHYSICAL_DEFENSE_DOWN,
    ETHER_DEFENSE_DOWN,
    PHYSICAL_ATTACK_DOWN,
    POTENTIAL_DOWN,
    BURN,
    POISON,
    PHYSICAL_ATTACK,
    ETHER_ATTACK
}
